version: '3.5'
services:
    varnish:
        image: vothanhphong/varnish:alpine
#        environment:
#            - VCL_CONFIG_PATH=/etc/varnish/myconfig/varnish.conf
#        volumes:
#            - ~/Docker/varnish.vcl:/etc/varnish/myconfig/varnish.vcl
        ports:
            - 80
        depends_on:
            - nginx
    redis:
        image: redis
        ports:
            - 6379
    elasticsearch:
        image: elasticsearch:5.4.0
        ports:
            - 9200
    nginx:
        image: vothanhphong/nginx
        ports:
            - 80:80
            - 443:443
        environment:
            - NGINX_CONFIG=
            - SERVER_NAME=docker.local
            - PHP_SERVICE=php
            - PHP_PORT=9000
            - ROOT_FOLDER=/project
            - IS_HTTPS=false
            - IS_MAGENTO=true
            - IS_MAGENTO_MULTI=false
            - MAGENTO_MODE= #developer or default or production
            - MAGENTO_RUN_TYPE= #store or website
            - MAGENTO_MULTI_SITES= # server_name1=store_code1 or website_code1;server_name2=store_code2 or website_code2 ...
        volumes:
            - ./docker/logs/nginx/:/var/log/nginx/
            - .:/project:rw
        depends_on:
            - php
    php:
        image: vothanhphong/fpm:7.1
        ports:
            - 9000
        environment:
            - IS_ACTIVE_XDEBUG=true
            - ENABLE_CRON=true
            - PHP_CONFIG=
            - FPM_POOL=
        volumes:
            - .:/project:rw
        depends_on:
            - db
            - redis
            - elasticsearch
    db:
        image: mariadb
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=local
            - MYSQL_USER=local
            - MYSQL_PASSWORD=local
            - MYSQL_ROOT_PASSWORD=local
        volumes:
            - ./docker/dbdata:/var/lib/mysql
    mail:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025
    rabbit:
        image: rabbitmq:3.8.4-management-alpine
        ports:
            - 15672:15672
