#!/bin/bash
set -e

NGINX_VHOST_PATH=/etc/nginx/sites-enabled/
mkdir -p "${NGINX_VHOST_PATH}"
rm -f "${NGINX_VHOST_PATH}"*

vhost "--folder=${ROOT_FOLDER}" \
    "--server-name=${SERVER_NAME}" \
    "--https=${HTTPS}" \
    "--path=${SUB_PATH}" \
    "--varnish-host=${VARNISH}" \
    "--project-type=${PROJECT_TYPE}" \
    "--varnish-port=${VARNISH_PORT}" \
    "--proxy-host=${PROXY}" \
    "--proxy-port=${PROXY_PORT}"

# Update nginx config
if [[ "${NGINX_CONFIG}" != '' ]]; then
    mapfile -t NGINX_CONFIG < <(echo "${NGINX_CONFIG}" | tr ',' "\n")
    nginx-config "${NGINX_CONFIG[@]}"
fi

for command in "$@"
do
    command=${command//' \ '/' '}
    $command
done

nginx -t

nginx -g "daemon off;"