ARG VERSION=14
ARG ALPINE=14

FROM node:${VERSION}-alpine${ALPINE}

MAINTAINER VooThanh DEV <voothanhphong@gmail.com>

ENV ROOT_FOLDER /project

RUN apk update && \
    apk add autoconf \
            automake \
            make \
            nasm \
            file \
            libtool \
            libjpeg \
            zlib-dev \
            libpng-dev \
    && rm -rf /tmp/* /var/cache/* /var/lib/apk/* /var/log/* /var/tmp/*
RUN mkdir -p ${ROOT_FOLDER} \
    && chown -R 1000:1000 "${ROOT_FOLDER}" \
    && chmod -R 0777 "${ROOT_FOLDER}"

WORKDIR ${ROOT_FOLDER}

USER 1000

CMD ["node"]